version: '3'
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - MAL_CLIENT_ID=${MAL_CLIENT_ID}
      - MAL_CLIENT_SECRET=${MAL_CLIENT_SECRET}
      - MAL_CALLBACK_URL=${MAL_CALLBACK_URL}
