export const MATHJS_API = 'http://api.mathjs.org/v4/?expr=';

export const CURRENCY_CONVERTER_API = (apiKey: string, query: string) =>
  `http://api.exchangeratesapi.io/v1/latest?access_key=${apiKey}&${query}`;

export const SAUCENAO_API = 'https://saucenao.com/search.php';
export const SAUCENAO_LOGO =
  'https://f-droid.org/repo/com.luk.saucenao/en-US/icon_hchmnK2H6QtbwWR4cV6mtdp_7xBJ7eSdIiulErczfOc=.png';
export const REGEX_DOMAIN_NAME_ONLY =
  /^(?:https?:\/\/)?(?:[^@/\n]+@)?(?:www\.)?([^:/?#\n]+)/;
export const NHENTAI_BASE_URL = 'https://nhentai.net';

export const SAUCENAO_SOURCES: Record<number, string> = {
  3: 'DoujinMangaLexicon',
  4: 'DoujinMangaLexicon',
  5: 'Pixiv',
  6: 'Pixiv',
  8: 'NicoNicoSeiga',
  9: 'Danbooru',
  10: 'Drawr',
  11: 'Nijie',
  12: 'Yandere',
  13: 'OpeningsMoe',
  16: 'Fakku',
  18: 'NHentai',
  19: 'TwoDMarket',
  20: 'MediBang',
  21: 'AniDB',
  22: 'AniDB',
  23: 'IMDb',
  24: 'IMDb',
  25: 'Gelbooru',
  26: 'Konachan',
  27: 'SankakuChannel',
  28: 'AnimePictures',
  29: 'E621',
  30: 'IdolComplex',
  31: 'bcyIllust',
  32: 'bcyCosplay',
  33: 'PortalGraphics',
  34: 'DeviantArt',
  35: 'Pawoo',
  36: 'MangaUpdates',
  37: 'MangaDex',
  371: 'MangaDex',
  38: 'H-Misc (ehentai)',
  39: 'ArtStation',
  40: 'FurAffinity',
  41: 'Twitter',
  42: 'FurryNetwork',
  43: 'Kemono',
  44: 'Skeb',
};

export const CURRENCIES: Record<string, string> = {
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudan Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTC: 'Bitcoin',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'New Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLP: 'Chilean Peso',
  CNY: 'Chinese Yuan',
  COP: 'Colombian Peso',
  CRC: 'Costa Rican Colón',
  CZK: 'Czech Republic Koruna',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  EUR: 'Euro',
  GBP: 'British Pound Sterling',
  GEL: 'Georgian Lari',
  GHS: 'Ghanaian Cedi',
  HKD: 'Hong Kong Dollar',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Sheqel',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Króna',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KZT: 'Kazakhstani Tenge',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  MAD: 'Moroccan Dirham',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  NGN: 'Nigerian Naira',
  NOK: 'Norwegian Krone',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PEN: 'Peruvian Nuevo Sol',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Zloty',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RUB: 'Russian Ruble',
  SAR: 'Saudi Riyal',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  THB: 'Thai Baht',
  TRY: 'Turkish Lira',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  USD: 'United States Dollar',
  UYU: 'Uruguayan Peso',
  VND: 'Vietnamese Dong',
  ZAR: 'South African Rand',
};
